apiVersion: v1
# kubernetes must find storage that fit these criteria
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    # can be used by a single node, kubernetes must find an instance that has this storage mode and this must storage
    - ReadWriteOnce
  resources:
    requests:
      # find storage option statically or dynamically
      storage: 1Gi